### ISSUE TITLE
CSRF error with latest version of MISP

### ISSUE THREAD

**Issue by adpaccent** [MISP/misp-docker#174]
Hi Stefano,

This issue is still present. I tested 2.4.198 and the latest versions of misp-core and misp-modules, I configured Redis with the password and the CSRF error is still present. 

**You have tripped the cross-site request forgery protection of MISP
CSRF error: This happens usually when you try to resubmit the same form with invalidated CSRF tokens or you had a form open too long and the CSRF tokens simply expired. Just go back to the previous page and refresh the form (by reloading the same url) so that the tokens get refreshed.

Alternatively, click [here](https://misp-cert.enel.com/) to continue to the start page.**

This issue is not acceptable, because with CSRF error it's impossible to login into MISP and use it for everyday activities.

Please re-open this issue and fix it as soon as possible.

Let us know

_Originally posted by @adpaccent in https://github.com/MISP/misp-docker/issues/168#issuecomment-2439041351_

**Comment by ostefano** [comment]
Hi @adpaccent 

Folks have been using 2.5 without issues, so the issue is unlikely to be related to the docker image itself.
Most of the times issue with CSRF are due to erroneously set BASE_URL.

I would invite you to join the Gitter channel for more support as detailed here https://www.misp-project.org/support/
Also, make sure to provide logs when explaining your issue.

This is being closed in the meanwhile.

**Comment by adpaccent** [comment]
Hi @ostefano,

Before closing the ticket, I’d like us to discuss it to see if there’s really a problem. No rush.

The issue is that the REDIS_PASSWORD parameter does not accept passwords with special characters, such as ""L+<S6$Mw>phq". When using that password, the containers start up, but there’s a CSRF issue during login. It only works with passwords made up of letters and numbers.

I kindly ask you to reopen the issue, test the problem, and close it only after it has been resolved. We need to use stronger passwords now that Redis authentication is supported.

Please let me know.

Thanks!

**Comment by ostefano** [comment]
@adpaccent looks like you identified the root issue, and the current logic does not accept passwords with special characters. Something somewhere clearly fails because of that. The CSRF issues you are seeing are just the symptom and I would consider them unrelated.

Consider editing the issue title / description so it is clear what is it about, and I will be happy to re-open the issue.
Also, any further details would ease the fix on our side, so I am inviting you to investigate and provide more details.
With some luck you might even spot the issue and thus able to create a PR, which I will be happy to merge posthaste so a new image is promptly available.

I understand you want to use a more robust password, and this should be eventually fixed to support special characters.
However, since a workaround is available, the issue is non-critical, and this is an open source project, I can not guarantee this will be fixed in a timely manner.
