### ISSUE TITLE
REDIS_PASSWORD parameter does not support special characters

### ISSUE THREAD

**Issue by adpaccent** [MISP/misp-docker#175]
Hi,

I confirm that the REDIS_PASSWORD parameter does not accept passwords with special characters, such as ""L+<S6$Mw>phq". 

When using that password, the containers start up, but there’s a CSRF issue during login and the process does not work. 
It only works with simple passwords made up of letters and numbers.

Thanks!

**Comment by ostefano** [comment]
Likely to be related to the php ini session variable

**Comment by ostefano** [comment]
Did a quick investigation and found the following.

Clearly `docker-compose.yml` would benefit from this changeset to better support special characters:
```
diff --git a/docker-compose.yml b/docker-compose.yml
index d14deeb..9bdb497 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -13,9 +13,9 @@ services:

   redis:
     image: valkey/valkey:7.2
-    command: "--requirepass ${REDIS_PASSWORD:-redispassword}"
+    command: "--requirepass \"${REDIS_PASSWORD:-redispassword}\""
     healthcheck:
-      test: "valkey-cli -a ${REDIS_PASSWORD:-redispassword} ping || exit 1"
+      test: "valkey-cli -a \"${REDIS_PASSWORD:-redispassword}\" ping || exit 1"
       interval: 2s
       timeout: 1s
       retries: 3
```

However:
- '$' is interpreted by docker compose for variable expansion, you might want to escape it with another `$`.
- '>' and '<' (or `+`) are not handled properly by PHP when they are part of the save path. MISP errors out with the following even though `php.ini` is set correctly (shown in the UI as CSRF issue):
```
2024-10-27 11:09:01 Warning: Warning (2): session_start() [<a href='http://php.net/function.session-start'>function.session-start</a>]: Failed to read session data: redis (path: tcp://redis:6379?auth=L+&lt;S6Mw&gt;phq) in [/var/www/MISP/app/Lib/cakephp/lib/Cake/Model/Datasource/CakeSession.php, line 745]
Trace:
```

Given all this, and since this might even end up being a bug/unsupported feature in php or misp, I will *not* work on it.

You are welcome to further investigate whether php itself can work well when special characters are added to the save path (which normally hosts actual file paths, so they might sanitize special chars that are now there because we use the field to encode the password).

Happy for you or anybody else to work on this.

**Comment by ostefano** [comment]
@adpaccent turns out sed just wanted escaped replacement string.

Please test this extensively, with password with or without special characters (remember to escape '$' like this '$$').
