### ISSUE TITLE
AAD Auth not working

### ISSUE THREAD

**Issue by thezolin** [MISP/misp-docker#34]
Hello, 

I'm using CoolAcid container version on my production environment, and when I start the migration to this container, I've noticed the AAD authentication is not working or not supported anymore. 

I have the put all settings on config.php file and add cake module to bootstrap.php file also.

**Comment by ostefano** [comment]
Ack 👍 

Feel free to open a PR if you have enough spare cycles to work on it.

**Comment by thezolin** [comment]
Hi ostefano,

After investigation This line on configs/config.php file ...

![image](https://github.com/MISP/misp-docker/assets/36763110/92a416d6-9a90-4cb9-9d2b-a1f876ac7dc7)

...was changed to this:
![image](https://github.com/MISP/misp-docker/assets/36763110/b76c007a-b7f0-454f-90cc-78d5a3e4ab23)

Any idea what this behavior occurs?

**Comment by ostefano** [comment]
Because this setting is getting overwritten by `apply_critical_fixes` which is executed before `set_up_oidc` and `set_up_ldap`. If you want to use a new authenticator like AAD you need to edit the `core/files/configure_misp.sh`, implement something similar in spirit to `set_up_oidc` or `set_up_ldap` and rebuild the image / create a pull request.

**Comment by shieldsurge** [comment]
I had this same issue. Per @ostefano's suggestion, I implemented code similar to `set_up_oidc` and `set_up_ldap` within `core/files/configure_misp.sh`, and I created a pull request.
[https://github.com/MISP/misp-docker/pull/39](url)
