### ISSUE TITLE
Request for migration instructions from archived coolacid/docker-misp to official Docker image

### ISSUE THREAD

**Issue by sva-mk** [MISP/misp-docker#45]
## Problem

Our current MISP deployment is based on the no longer supported coolacid/docker-misp image. Due to the archived status of the associated GitHub repository and the lack of ongoing support, we need to migrate to the official image. 

Taking these circumstances into account, we are looking for instructions or a comprehensive migration guide for the transition to the official Docker image. It would be great if possible differences in the configurations, dependencies and database management between the two Docker images were pointed out and suitable migration solutions were specified.
## Previous attempts

We tried to follow the instructions given in issue [#2237](https://github.com/MISP/MISP/issues/2237) for migrating MISP data without the context of Docker. However, this approach resulted in database instability, possibly due to differences such as the transition from MySQL to MariaDB in the official MISP Docker image.
## Support needed

Given the urgent need to migrate from the legacy Docker image, we are asking for support, documentation or best practices to enable a transition to the official MISP Docker image. Any insight, guidance or recommendations would be helpful to ensure a stable and reliable deployment.

Thank you in advance!

**Comment by ostefano** [comment]
There is no guide or pre-established knowledge/best practice for such migration.

Best shot is to ask in the chat channels for other folks' experiences.

Another thing you might want to try is attempting the DB migration again but also replace the DB image in the docker-compose file with the one you were using before with Coolacid's docker image.

This docker image does not depend on a specific MySQL/MariaDB version (MariaDB was picked because of compatibility with ARM and with MISP diagnostic tests).

I will close this issue since there is nothing we can do on our side besides what I mentioned.
