### ISSUE TITLE
Add support for Static IP.

### ISSUE THREAD

**Issue by DkYSwe** [MISP/misp-docker#5]
Hi,
Quite new to handling docker contains (but also new to MISP).

Everything builds as expected but I have a question. Can you implement to docker_compose.yml for static IP settings?
I will go for settings up a proxy on the host, thus wanting a static IP for the interface.

It would be great if you guys have a simple workaround to get statis IP assigned, while not implemented in the docker_compose.yml file.

All the best,
Daniel

**Comment by ostefano** [comment]
@DkYSwe wouldn't it be better to expose the 443 port (which is the default) and let clients connect to the IP of the host?

If you really really want to got that way you could check this thread on stackoverflow: https://stackoverflow.com/questions/39493490/provide-static-ip-to-docker-containers-via-docker-compose

Having said that, I am closing the issue since I don't plan to add this corner case since the `docker-compose.yml` file is already meant to be modified by the user.
