### ISSUE TITLE
Why enabling and disabling ZeroMQ

### ISSUE THREAD

**Issue by christianmg99** [MISP/misp-docker#55]
Hi, I was just wondering why ZeroMQ is first enabled:
https://github.com/MISP/misp-docker/blob/aeff7b3e3e33819b04fe8bb240147a43bc215ab5/core/files/configure_misp.sh#L27
And then disabled under the premise "Disable weird default"
https://github.com/MISP/misp-docker/blob/aeff7b3e3e33819b04fe8bb240147a43bc215ab5/core/files/configure_misp.sh#L212

**Comment by ostefano** [comment]
<strike>There was a valid reason, but that was 2 years ago 😅 I will try to rebuild the reasoning and post it there, likely when I have time to test the whole thing again.

UPDATE: I believe it is started by MISP itself when needed, but for the sake of the update I had to enable it because it is meant to be run unattended. Then disabling it again it is to catch errors when the user first logins. </strike>

@christianmg99 alright, reconstructed the logic: so, ZMQ is needed when running updates, but that is it. No core functionality of MISP requires ZMQ, and since updates are ran by the dockerization itself, there is no reason to enable it by default.

Having said that the user is more than welcome to just flip the flag in the settings page (just did in my test instance and the diagnostic page says that the ZMQ works as expected).

Happy to re-open if we find a reason to enable it by default.
