### ISSUE TITLE
provisioning process gets stuck in await_system_settings_table

### ISSUE THREAD

**Issue by damanzanofortra** [MISP/misp-docker#73]
Image: v2.4.193
Environment: k8s

My pod gets stuck awaiting on [await_system_settings_table](https://github.com/MISP/misp-docker/blob/master/core/files/configure_misp.sh#L364).

I noticed the systems_settings table is not part of the initial installation script in the official MISP https://github.com/MISP/MISP/blob/v2.4.193/INSTALL/MYSQL.sql but as part of the app model update https://github.com/MISP/MISP/blob/462088e88698bac16aee1b266850dc8931e5987e/app/Model/AppModel.php#L1654. So, wondering if this CLI configuration step https://github.com/MISP/misp-docker/blob/master/core/files/configure_misp.sh#L438C1-L438C76 should be executed at a later stage

**Comment by ostefano** [comment]
Good point. @UFOSmuggler this is a regression.

We should not rely on this table until all updates are run.
Postponing the CLI configuration step is not the solution because `apply_updates` requires some of those settings to be inplace.

**Comment by ostefano** [comment]
@damanzanofortra I am regenerating the images with that line commented, but I will leave this open since the fix is clearly a workaround and I would like @UFOSmuggler to review it (here the commit https://github.com/MISP/misp-docker/commit/303ea9d2f9e02735f9dae0e0866c0520ccc102f1)

**Comment by damanzanofortra** [comment]
Awesome! Thanks

**Comment by UFOSmuggler** [comment]
hi @damanzanofortra

thanks for your issue!  i am chasing down the behaviour since i am seeing it operate in a different fashion.  i have a fix ready but just want to check if a suspicion is correct, or if i need to do additional work.

~~could you please let me know if you are using the repo supplied docker-compose.yml file, or if you have commented out the misp-core container health checks, or something?~~

i see you are using k8s, so may not have implemented the same health checks.

from what i can see, and from what i experience running up fresh containers, the health checks run by the misp-core container should cause runUpdates to run, which should create that table pretty quickly.

the fix i intend to provide will remove this unintentional dependency upon the health checks regardless.

**Comment by damanzanofortra** [comment]
@UFOSmuggler No, I haven't disabled the health checks in the docker compose. In this case I'm using the image in a kubernetes deployment and I did configure the health check properties the same way as the provided docker compose file
```
Liveness:   http-get https://localhost/users/login
Readiness:  http-get https://localhost/users/login
```
The issue happens on a fresh installs

**Comment by UFOSmuggler** [comment]
ok, thanks.  i'll proceed with my planned fix which should address this irrespective.
